//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        //----------------------------------- FirstPageOfOption --------------------------------------------------

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\_SWLIB_\\Базы данных\\")]
        
        public string DBPath
        {
            get
            {
                return ((string)(this["DBPath"]));
            }
            set
            {
                this["DBPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\_SWLIB_\\Чертежи\\")]
        public string DrwPath
        {
            get
            {
                return ((string)(this["DrwPath"]));
            }
            set
            {
                this["DrwPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\_SWLIB_\\")]
        public string ModelPath
        {
            get
            {
                return ((string)(this["ModelPath"]));
            }
            set
            {
                this["ModelPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\_SWLIB_\\Декоры\\")]
        public string DecorPath
        {
            get
            {
                return ((string)(this["DecorPath"]));
            }
            set
            {
                this["DecorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectIniPath
        {
            get
            {
                return ((string)(this["ConnectIniPath"]));
            }
            set
            {
                this["ConnectIniPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SCENTRE1")]
        public string ConnectParameterName
        {
            get
            {
                return ((string)(this["ConnectParameterName"]));
            }
            set
            {
                this["ConnectParameterName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OraDbLogin
        {
            get
            {
                return ((string)(this["OraDbLogin"]));
            }
            set
            {
                this["OraDbLogin"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OraDbPassword
        {
            get
            {
                return ((string)(this["OraDbPassword"]));
            }
            set
            {
                this["OraDbPassword"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Designer
        {
            get
            {
                return ((string)(this["Designer"]));
            }
            set
            {
                this["Designer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("devout@mrdoors.ru")]
        public string MailFrom
        {
            get
            {
                return ((string)(this["MailFrom"]));
            }
            set
            {
                this["MailFrom"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a.nikitina@mrdoors.ru")]
        public string MailTo
        {
            get
            {
                return ((string)(this["MailTo"]));
            }
            set
            {
                this["MailTo"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("delta.mrdoors.ru")]
        public string MailHost
        {
            get
            {
                return ((string)(this["MailHost"]));
            }
            set
            {
                this["MailHost"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Coca12")]
        public string MailHostPass
        {
            get
            {
                return ((string)(this["MailHostPass"]));
            }
            set
            {
                this["MailHostPass"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoggingOn
        {
            get
            {
                return ((bool)(this["LoggingOn"]));
            }
            set
            {
                this["LoggingOn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FatalMailOn
        {
            get
            {
                return ((bool)(this["FatalMailOn"]));
            }
            set
            {
                this["FatalMailOn"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateProgramsOnFF
        {
            get
            {
                return ((bool)(this["CreateProgramsOnFF"]));
            }
            set
            {
                this["CreateProgramsOnFF"] = value;
            }
        }
        //-------------------------------------- SecondPage ------------------------------------------------------

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveComponents
        {
            get
            {
                return ((bool)(this["AutoSaveComponents"]));
            }
            set
            {
                this["AutoSaveComponents"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveDrawings
        {
            get
            {
                return ((bool)(this["AutoSaveDrawings"]));
            }
            set
            {
                this["AutoSaveDrawings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoShowSetParameters
        {
            get
            {
                return ((bool)(this["AutoShowSetParameters"]));
            }
            set
            {
                this["AutoShowSetParameters"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCutOff
        {
            get
            {
                return ((bool)(this["AutoCutOff"]));
            }
            set
            {
                this["AutoCutOff"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRecalculateOnAdd
        {
            get
            {
                return ((bool)(this["AutoRecalculateOnAdd"]));
            }
            set
            {
                this["AutoRecalculateOnAdd"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckCavitiesCross
        {
            get
            {
                return ((bool)(this["CheckCavitiesCross"]));
            }
            set
            {
                this["CheckCavitiesCross"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImmediatelyDetachModel
        {
            get
            {
                return ((bool)(this["ImmediatelyDetachModel"]));
            }
            set
            {
                this["ImmediatelyDetachModel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReloadComponents
        {
            get
            {
                return ((bool)(this["ReloadComponents"]));
            }
            set
            {
                this["ReloadComponents"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetDecorsFromFirstElement
        {
            get
            {
                return ((bool)(this["SetDecorsFromFirstElement"]));
            }
            set
            {
                this["SetDecorsFromFirstElement"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScaleWhenDimen
        {
            get
            {
                return ((bool)(this["ScaleWhenDimen"]));
            }
            set
            {
                this["ScaleWhenDimen"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewsBeforeDimen
        {
            get
            {
                return ((bool)(this["ViewsBeforeDimen"]));
            }
            set
            {
                this["ViewsBeforeDimen"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckParamLimits
        {
            get
            {
                return ((bool)(this["CheckParamLimits"]));
            }
            set
            {
                this["CheckParamLimits"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertToDwgPdf
        {
            get
            {
                return ((bool)(this["ConvertToDwgPdf"]));
            }
            set
            {
                this["ConvertToDwgPdf"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreatePacketHoles
        {
            get
            {
                return ((bool)(this["CreatePacketHoles"]));
            }
            set
            {
                this["CreatePacketHoles"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetParentWindow
        {
            get
            {
                return ((bool)(this["SetParentWindow"]));
            }
            set
            {
                this["SetParentWindow"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CashModeOn
        {
            get
            {
                return ((bool)(this["CashModeOn"]));
            }
            set
            {
                this["CashModeOn"] = value;
                Cash.RaiseCashModeChangedEvent();
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KitchenModeOn
        {
            get
            {
                return ((bool)(this["KitchenModeOn"]));
            }
            set
            {
                this["KitchenModeOn"] = value;
                KitchenModule.RaiseKitchenModeChangedEvent();                
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CashModeAvailable
        {
            get
            {
                return ((bool)(this["CashModeAvailable"]));
            }
            set
            {
                this["CashModeAvailable"] = value;
                Cash.RaiseCashModeAvailableChangedEvent();
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KitchenModeAvailable
        {
            get
            {
                return ((bool)(this["KitchenModeAvailable"]));
            }
            set
            {
                this["KitchenModeAvailable"] = value;
                KitchenModule.RaiseKitchenModeAvailableChangedEvent();  
            }
        }


        // ------------------------------------------- ThirdPage ---------------------------------------------------

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckUpdateLib
        {
            get
            {
                return ((bool)(this["CheckUpdateLib"]));
            }
            set
            {
                this["CheckUpdateLib"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31.12.2010 23:59:00")]
        public string PatchVersion
        {
            get
            {
                return ((string)(this["PatchVersion"]));
            }
            set
            {
                this["PatchVersion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftpsolidRO")]
        public string NameFtpUserForLibUpdate // имя пользователя для доступа к ftp с библиотекой
        {
            get
            {
                return ((string)(this["NameFtpUserForLibUpdate"]));
            }
            set
            {
                this["NameFtpUserForLibUpdate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ds36btr")]
        public string SecureFtpUser // пароль пользователя для доступа к ftp с библиотекой
        {
            get
            {
                return ((string)(this["SecureFtpUser"]));
            }
            set
            {
                this["SecureFtpUser"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public string AdmUsrName // имя пользователя с администраторскими правами для обновления программы
        {
            get
            {
                return ((string)(this["AdmUsrName"]));
            }
            set { this["AdmUsrName"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Qp67ySh")]
        public string AdmUsrPsw  // пароль пользователя с администраторскими правами для обновления программы
        {
            get
            {
                return ((string)(this["AdmUsrPsw"]));
            }
            set { this["AdmUsrPsw"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://194.84.146.5/")] /// Заменили на динамический тип 

        
        public string FurnFtpPath  // путь для обновления программы
        {
            get
            {
                return ((string)(this["FurnFtpPath"]));
            }
            set { this["FurnFtpPath"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("solidk")]
        public string FurnFtpName  // имя пользователя для обновления программы
        {
            get
            {
                return ((string)(this["FurnFtpName"]));
            }
            set { this["FurnFtpName"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KSolid")]
        public string FurnFtpPass  // пароль пользователя для обновления программы
        {
            get
            {
                return ((string)(this["FurnFtpPass"]));
            }
            set { this["FurnFtpPass"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateToTest  // пароль пользователя для обновления программы
        {
            get
            {
                return ((bool)(this["UpdateToTest"]));
            }
            set { this["UpdateToTest"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FtpPath
        {
            get
            {
                return ((string)(this["FtpPath"]));
            }
            set
            {
                this["FtpPath"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRPDBefore
        {
            get
            {
                return ((bool)(this["ShowRPDBefore"]));
            }
            set
            {
                this["ShowRPDBefore"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoArrangeDimension
        {
            get
            {
                return ((bool)(this["AutoArrangeDimension"]));
            }
            set
            {
                this["AutoArrangeDimension"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteBeforeDim
        {
            get
            {
                return ((bool)(this["DeleteBeforeDim"]));
            }
            set
            {
                this["DeleteBeforeDim"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultRPDView
        {
            get
            {
                return ((bool)(this["DefaultRPDView"]));
            }
            set
            {
                this["DefaultRPDView"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteDraftIfStandart
        {
            get
            {
                return ((bool)(this["DeleteDraftIfStandart"]));
            }
            set
            {
                this["DeleteDraftIfStandart"] = value;
            }
        }

        //-------------------------------------- CodeForSecurity-------------------------------------------------

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppRegCode
        {
            get
            {
                return ((string)(this["AppRegCode"]));
            }
            set
            {
                this["AppRegCode"] = value;
            }
        }
    }
}
